# Generated by Django 4.1.3 on 2022-11-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('forConference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.conference')),
            ],
        ),
    ]
