# Generated by Django 4.1.3 on 2022-11-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
