# Generated by Django 4.1.3 on 2022-11-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_rename_location_stadium_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('titlesWon', models.IntegerField()),
                ('gamesWon', models.IntegerField()),
                ('gamesLost', models.IntegerField()),
                ('dateFounded', models.DateField()),
                ('fans', models.IntegerField()),
                ('sponsors', models.IntegerField()),
                ('logo', models.CharField(max_length=1000)),
                ('hasStadium', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.stadium')),
                ('inDivision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.division')),
            ],
        ),
    ]
