# Generated by Django 4.1.3 on 2022-11-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_game_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('yearsOfCoaching', models.IntegerField()),
                ('university', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.coach'),
        ),
    ]
