# Generated by Django 4.1.3 on 2022-11-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_referee_game_referee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='inTeam',
        ),
        migrations.RemoveField(
            model_name='scout',
            name='forTeam',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.CreateModel(
            name='Team_Scout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.scout')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.team')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.team')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.team')),
            ],
        ),
    ]
