# Generated by Django 4.1.3 on 2022-11-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
    ]
