# Generated by Django 4.1.3 on 2022-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_game_inseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
