# Generated by Django 4.1.3 on 2022-12-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='inDivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.division'),
        ),
    ]
